pipeline {
    agent { node { label 'maven' } }
    environment { APP_NAMESPACE = 'jomcdona-recover' }
    stages {
        stage('Test') {
            steps {
                options { timeout(time: 50, unit: 'SECONDS') }
                dir('shopping-cart-v2') {
                    sh './mvnw clean test'
                }
            }
        }
    }
}
